// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2WPqw9gCk45POCK-Thlgxk11VBuB_-cM',
    appId: '1:371987695696:web:c7b5bb0fd2a1ebe94fa955',
    messagingSenderId: '371987695696',
    projectId: 'pacc-app-ef490',
    authDomain: 'pacc-app-ef490.firebaseapp.com',
    storageBucket: 'pacc-app-ef490.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhwVbxGGm1wMq7wzmkZp1I7yZxjc0y2tY',
    appId: '1:371987695696:ios:d2885a2160ea051b4fa955',
    messagingSenderId: '371987695696',
    projectId: 'pacc-app-ef490',
    storageBucket: 'pacc-app-ef490.firebasestorage.app',
    iosClientId: '371987695696-84hfl4bjjo5iii54i8hpebbgk8bvb7l9.apps.googleusercontent.com',
    iosBundleId: 'com.example.testt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhwVbxGGm1wMq7wzmkZp1I7yZxjc0y2tY',
    appId: '1:371987695696:ios:d2885a2160ea051b4fa955',
    messagingSenderId: '371987695696',
    projectId: 'pacc-app-ef490',
    storageBucket: 'pacc-app-ef490.firebasestorage.app',
    iosClientId: '371987695696-84hfl4bjjo5iii54i8hpebbgk8bvb7l9.apps.googleusercontent.com',
    iosBundleId: 'com.example.testt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2WPqw9gCk45POCK-Thlgxk11VBuB_-cM',
    appId: '1:371987695696:web:f43df71871058ce14fa955',
    messagingSenderId: '371987695696',
    projectId: 'pacc-app-ef490',
    authDomain: 'pacc-app-ef490.firebaseapp.com',
    storageBucket: 'pacc-app-ef490.firebasestorage.app',
  );
}
